### ISSUE TITLE
Test support for batches in all transforms

### ISSUE THREAD

**Issue by iver56** [asteroid-team/torch-audiomentations#1]
The first dimension should represent batches

**Comment by francislata** [comment]
I agree. Please note the discussion here: https://github.com/asteroid-team/torch-audiomentations/pull/5#discussion_r493878206 as it talks about having the first dimension representing the batch size, while the second dimension represents the number of channels - if it is a mono audio, then it will have a value of 1.

Changes to this are already made in the PR where the aforementioned link points to.
