### ISSUE TITLE
bump python version to 3.9 (part 2)

### ISSUE THREAD

**Issue by SolomidHero** [asteroid-team/torch-audiomentations#109]
Maybe we should apply for all 3.9 versions (there would be safety updates), since 3.10 released?

**Comment by iver56** [comment]
Yeah, I already [did that](https://github.com/asteroid-team/torch-audiomentations/commit/1a905acd1b8466a4250b5b68002f92375908efb4), but it's not released to PyPI atm. I'll make it happen.

**Comment by iver56** [comment]
https://pypi.org/project/torch-audiomentations/0.9.1/
