### ISSUE TITLE
[Bug] RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu

### ISSUE THREAD

**Issue by ahikaml** [asteroid-team/torch-audiomentations#137]
Hi, 
It happens in band_pass_filter.py 
_bandwidth_dist_ is allocated on the CPU (ln 101-103) while _center_dist_ (ln96-98) is allocated on the GPU.
I think that it can be solved by using the device info of _selected_samples_ for _bandwidth_dist_ .

**Comment by iver56** [comment]
Ok, yeah, that should be fixed. I'll see if I can patch it real quick

**Comment by iver56** [comment]
https://github.com/asteroid-team/torch-audiomentations/pull/138
