### ISSUE TITLE
Could you please claim those augmentations that are differentiable?

### ISSUE THREAD

**Issue by xinghua-qu** [asteroid-team/torch-audiomentations#152]
Hi, thanks for providing this package for audio augmentation.

Currently, I am trying to introduce these augmentations into a forward function of torch model. However, some of them are not differentiable.
Could you please mark out those differentiable ones and those not?

Many thanks from Singapore!

**Comment by iver56** [comment]
Hi :) There is a .py-file for differentiability tests in the tests folder. You can see there that some transforms are intentionally skipped because they are not differentiable. I am on vacation right now, so I cannot do much more than this right now.

Also note that you can make parts of your nn.Module "not differentiable" so it doesn't try to differentiate things that do not need it

**Comment by xinghua-qu** [comment]
> Hi :) There is a .py-file for differentiability tests in the tests folder. You can see there that some transforms are intentionally skipped because they are not differentiable. I am on vacation right now, so I cannot do much more than this right now.
> 
> Also note that you can make parts of your nn.Module "not differentiable" so it doesn't try to differentiate things that do not need it

Hi :)

Many thanks for the quick reply. The `test-differentiable.py` did tell which augmentation is differentiable.

However, I do meet another issue, i.e., the `ApplyImpulseResponse()` function makes the training extremely slow. Any idea on such issue?

Thanks in advance and wish you a wonderful vacation:)

**Comment by iver56** [comment]
> ApplyImpulseResponse()

Check if your impulse response files and your audio inputs have the same sample rate. If not, you may see a slowdown.

Also, it is recommended to load the files from SSD, as HDD may become a bottleneck.

The convolution itself should be pretty fast, especially if it gets run on a decent GPU and with batched compute

**Comment by xinghua-qu** [comment]
> > ApplyImpulseResponse()
> 
> Check if your impulse response files and your audio inputs have the same sample rate. If not, you may see a slowdown.
> 
> Also, it is recommended to load the files from SSD, as HDD may become a bottleneck.
> 
> The convolution itself should be pretty fast, especially if it gets run on a decent GPU and with batched compute

That's great!!! Many thanks for the help:)

**Comment by xinghua-qu** [comment]
> > ApplyImpulseResponse()
> 
> Check if your impulse response files and your audio inputs have the same sample rate. If not, you may see a slowdown.
> 
> Also, it is recommended to load the files from SSD, as HDD may become a bottleneck.
> 
> The convolution itself should be pretty fast, especially if it gets run on a decent GPU and with batched compute



> > ApplyImpulseResponse()
> 
> Check if your impulse response files and your audio inputs have the same sample rate. If not, you may see a slowdown.
> 
> Also, it is recommended to load the files from SSD, as HDD may become a bottleneck.
> 
> The convolution itself should be pretty fast, especially if it gets run on a decent GPU and with batched compute

Hi Iver,

One more question for adding background noise ``AddBackgroundNoise('./background_noise/environment/0.wav', 30, p=1.0). 
For adding background noise, using the path of a wav file, e.g., `./background_noise/environment/0.wav` causes the error below.

`TypeError: Invalid file: PosixPath('/xxxxx/background_noise/environment/0.wav')`

Any idea on the reason for such issue

**Comment by iver56** [comment]
Hmm what if you give it a directory instead of a file? And what version of torch-audiomentations are you using?

**Comment by iver56** [comment]
Then I don't know. Can you try step-debugging it?

**Comment by xinghua-qu** [comment]
> Then I don't know. Can you try step-debugging it?

Sure. Thanks.

**Comment by xinghua-qu** [comment]
For any people else who may also meet the same issue of `TypeError: Invalid file: PosixPath('/xxxxx/background_noise/environment/0.wav')`.

The follow command can help.
`torchaudio.set_audio_backend("sox_io")`

Solution is inspired by [`Improving I/O for correct and consistent experience #903`](https://github.com/pytorch/audio/issues/903)
