### ISSUE TITLE
RandomCrop does not work on GPU

### ISSUE THREAD

**Issue by miccio-dk** [asteroid-team/torch-audiomentations#153]
Hi everyone, 
thanks for the really cool library.
The `RandomCrop` augmentation forces my data to be on the CPU. After looking into the code (and some of the similar issues here), it seems that the `samples_cropped` variable needs to have its device specified. I will submit a pull request soon with the change, let me know if I should write a test for it (not very familiar with testing but I can try).

**Comment by iver56** [comment]
RandomCrop wasn't officially released yet due to its state. Thanks for helping it become ready for release :)
