### ISSUE TITLE
AddColoredNoise: reasoning for f_decay being sampled from uniform distribution?

### ISSUE THREAD

**Issue by fujikosu** [asteroid-team/torch-audiomentations#160]
Hi, thanks for the great library! I'm trying to use this library, specifically AddColoredNoise to add pink noise to the input audio as part of data augmentation for deep learning training and I got two questions.

I see that AddColoredNoise class takes `min_f_decay: float` and `max_f_decay: float` as inputs. And actual f_decay for noise is sampled from uniform distribution between min_f_decay and max_f_decay as follows:

```py
        for param, mini, maxi in [
            ("snr_in_db", self.min_snr_in_db, self.max_snr_in_db),
            ("f_decay", self.min_f_decay, self.max_f_decay),
        ]:
            dist = torch.distributions.Uniform(
                low=torch.tensor(mini, dtype=torch.float32, device=samples.device),
                high=torch.tensor(maxi, dtype=torch.float32, device=samples.device),
                validate_args=True,
            )
            self.transform_parameters[param] = dist.sample(sample_shape=(batch_size,))
```

Based on my understanding, to generate pink noise, f_decay needs to be 1. To do that, I specified min_f_decay=1 and max_f_decay=1 and I got this error below as low and high take the same values in Uniform now.

```py
>           raise ValueError("Uniform is not defined when low>= high")
E           ValueError: Uniform is not defined when low>= high

/opt/conda/envs/noise-dl/lib/python3.9/site-packages/torch/distributions/uniform.py:58: ValueError
```

Here are two questions I got

- Is my understanding correct that pink noise needs f_decay to be 1? (I'm new to this audio domain)
- Is there any reason why this method uses random sampling over taking static f_decay as input?

**Comment by iver56** [comment]
Hi fujikosu!
Good point, we should ideally add support for self.min_f_decay == self.max_f_decay

A possible workaround until it is fixed is to do something like
```
min_f_decay=1.0,
max_f_decay=1.0000001
```

I'm afraid I don't know so much about the details of AddColoredNoise :/ It was made by @amiasato in 2021. According to his docstring, f_decay should indeed be 1 for pink noise

> Is there any reason why this method uses random sampling over taking static f_decay as input?

In the spirit of data augmentation, the intention with this technique was to make it have more variety in what it does, compared to using just a static f_decay

**Comment by fujikosu** [comment]
Thanks for the explanation, @iver56. That makes sense!

**Comment by iver56** [comment]
https://github.com/asteroid-team/torch-audiomentations/pull/162
