### ISSUE TITLE
Why is RMS norm used in AddBackgroundNoise?

### ISSUE THREAD

**Issue by jp1924** [asteroid-team/torch-audiomentations#166]
I was looking at AddBackgroundNoise and had some questions.      

1. why are you doing RMS_norm when adding noise to raw audio?
    
2. and AddBackgroundNoise only applies RMS to the noise, but the augmentation code provided in the [MS-SNSD](https://github.com/microsoft/MS-SNSD/blob/master/audiolib.py#L55-L71) repo does RMS_norm for both raw audio and noise, what is the difference?
    
3. looking at torchaudio's [add_noise](https://github.com/pytorch/audio/blob/main/torchaudio/functional/functional.py#L2396-L2397), it uses L2_norm, can I replace RMS with L2_norm?

**Comment by iver56** [comment]
You closed your issue. Does that mean you figured it out yourself?

**Comment by jp1924** [comment]
Yes, that's right.
The formula for SNR made sense to me, so I closed the issue.
