### ISSUE TITLE
Add `train()` method?

### ISSUE THREAD

**Issue by hbredin** [asteroid-team/torch-audiomentations#22]
Suppose I define `MyNetwork` with built-in augmentation like this:

```python
import torch
import torch.nn as nn
from torch_audiomentations import Gain

class MyNetwork(nn.Module):
    def __init__(self):
        self.augmentation = Gain(min_gain_in_db=-15.0, max_gain_in_db=5.0, p=0.5)
        self.other_layers = ...

    def foward(self, waveforms):
        augmented_waveforms = self.augmentation(waveforms)
        return self.other_layers(augmented_waveforms)

net = MyNetwork()
```        

As per my understanding of current code base, calling `net.train(mode=False)` (aka `net.eval()`) has no effect on `net.augmentation`. Augmentation will always be applied, whether we call `net.eval()` or not.

Would it make sense to add the following method to `BaseWaveformTransform` so that one can activate/deactivate augmentations with `net.train(mode=...)`?

```python
class BaseWaveformTransform(nn.Module):
    def train(self, mode: bool = True):
        if mode:
            self.p = self._p_backup
        else:
            self._p_backup = self.p
            self.p = 0.0
```

The `_p_backup` hack is ugly and the whole `p` management should probably be rewritten but you get the idea. What do you think?

**Comment by iver56** [comment]
So far, I've been doing something like this:

```
class MyNetwork(nn.Module):
    (...)
    
    def forward(self, x):
        (...)

        if self.training:
            # perform augmentation here
        else:
            pass
        (...)
```

But yeah, we should probably implement eval properly. I would accept a pull request for this

**Comment by hbredin** [comment]
OK. I'll try to come up with a PR.

Should I stick with the above `p_backup` hack or should I also rewrite the `p` property getter/setter methods?

**Comment by iver56** [comment]
If we can do `if not self.training: return samples  # no op` inside `BaseWaveformTransform.forward()`, that would be a simple way to do it, I think. I don't know how/if `my_model.train()` / `my_movel.eval()` propagates to submodules.

**Comment by hbredin** [comment]
It is propagated to `.children()`: 

https://github.com/pytorch/pytorch/blob/0c5cd8c2b9cdf473e30bbb1b49ca80ed442813df/torch/nn/modules/module.py#L1275-L1278

So, your suggestion is much better indeed.
