### ISSUE TITLE
Merge test_requires (in setup.py) with .github/workflows/test_requirements.txt

### ISSUE THREAD

**Issue by iver56** [asteroid-team/torch-audiomentations#33]

**Comment by mpariente** [comment]
It seems that the repo is installed automatically during CI, but without the `test_requires`. 
I don't know how to handle that elegantly and avoid to clone and install again.. 
Maybe by moving into `extras_require`? IDK

**Comment by iver56** [comment]
I think the case for specifying `tests_require=` is when you want to do `python setup.py test`

https://python-packaging.readthedocs.io/en/latest/testing.html

Since we're not doing that, I'll go ahead and remove it
