### ISSUE TITLE
Sample Rate in the forward

### ISSUE THREAD

**Issue by mogwai** [asteroid-team/torch-audiomentations#40]
I'm sure a lot of people working with torch-audiomentations will want to use some of the transforms available in torchaudio, at least for now until #4 is ready. I noticed that the sample rate was required for the forward call of the BaseWaveTransforms? This means that I have to check in a list of transforms to invoke the forward correctly. Would it not be better to have the sample_rate initialised as part of the init?

**Comment by iver56** [comment]
> This means that I have to check in a list of transforms to invoke the forward correctly.

I don't understand this. Can you elaborate? Maybe by example?

**Comment by mogwai** [comment]
```py
from torchaudio.transforms import Resample, MFCC, FrequencyMask
import torch
from torch_audiomentations.augmentations.gain import Gain

#32 waveforms, 2 seconds in length
batch, sr = torch.rand(32,1,32000), 16000

# List of transforms
tfms = [Resample(), Gain(), MFCC(), FrequencyMask(20)]

for tfm in tfms:
  # breaks because gain expects sample_rate in the forward
  batch = tfm(batch)
```

It's not a huge issue to work around that but it would it not be cleaner to pass the `BaseWaveTransformation` an sr to work with if it needs it?

```py
tfms = [Resample(), Gain(16000), MFCC(), FrequencyMask(20)]
```

It is also the case that several of the transforms do not even require the sr. (Gain, PeakNormalisation,..) so maybe it should be something they have initialised in their own init methods? Then they can access the sample_rate with `self.sample_rate`?

**Comment by iver56** [comment]
I see. Perhaps you could join our slack? We could discuss the two options there

**Comment by iver56** [comment]
My conclusion from yesterday's discussion on slack:

* Make sample_rate in forward optional
* Add an optional sample_rate argument in the init of the transform
* Sample rate can be specified in transform init or in forward. If specified in both, the one specified in forward will be used
* We do not have to pass a sample rate to transforms that do not care about sample rate. This applies to e.g. `Gain`, `PolarityInversion` and `PeakNormalization`
* If a required sample rate is missing, an exception will be raised in forward

**Comment by mogwai** [comment]
That sounds really flexible. Checks can be made by the individual transform itself sounds like a good addition as well.
