### ISSUE TITLE
Add high-pass filter and low-pass filter

### ISSUE THREAD

**Issue by iver56** [asteroid-team/torch-audiomentations#43]
@nicofarr
ref https://github.com/brain-bzh/dcase-2020-task1-subtaskB/blob/master/create_dataset.py

**Comment by nicofarr** [comment]
Great, let's try to work on this soon. Maybe @npaj can help here?

**Comment by iver56** [comment]
https://github.com/asteroid-team/torch-audiomentations/pull/81
