### ISSUE TITLE
Update find_audio_files to look into subfolders as well

### ISSUE THREAD

**Issue by hbredin** [asteroid-team/torch-audiomentations#55]
I just downloaded [EchoThief](http://www.echothief.com/) RIRs and naively thought the find_audio_files would look into subfolders. It did not and I got a nice error message telling me it could find any audio file...

The reason is that EchoThief RIRs are stored in subfolders by category.
We should update find_audio_files to look into subfolders.

**Comment by iver56** [comment]
Let's copy this one:
https://github.com/iver56/audiomentations/blob/master/audiomentations/core/utils.py#L9
