### ISSUE TITLE
Any plans to support more audio effects like pitchshift, etc.?

### ISSUE THREAD

**Issue by YuanxunLu** [asteroid-team/torch-audiomentations#57]
Such a wonderful work! Is there any plan to implement audio effects like pitch-shift, reverb, equalizer, etc?

**Comment by iver56** [comment]
Thanks! Yes. Want to contribute?

**Comment by YuanxunLu** [comment]
Waiting for it! Currently, I'm just an ant on hot pots cause my paper's ddl :(

**Comment by iver56** [comment]
I split this issue

* https://github.com/asteroid-team/torch-audiomentations/issues/67
* https://github.com/asteroid-team/torch-audiomentations/issues/66
* https://github.com/asteroid-team/torch-audiomentations/issues/38
