### ISSUE TITLE
Failure in test_utils.py

### ISSUE THREAD

**Issue by francislata** [asteroid-team/torch-audiomentations#6]
@iver56 - there's a failure to the assertion when comparing the PyTorch way of convolving versus scipy's version. I have made one small change [here](https://github.com/asteroid-team/torch-audiomentations/pull/5/files) to match the required arguments as specified in [numpy's documentation](https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_almost_equal.html).

**Comment by iver56** [comment]
I've seen that failure too. My solution was to set `decimal=6` in `assert_almost_equal()`. The default is 7.

**Comment by francislata** [comment]
Should I apply this change in my pull request for adding impulse response transformation?

**Comment by iver56** [comment]
Yes please

**Comment by iver56** [comment]
Closed by https://github.com/asteroid-team/torch-audiomentations/pull/5
