### ISSUE TITLE
Optionally compensate for propagation delay in ApplyImpulseResponse

### ISSUE THREAD

**Issue by iver56** [asteroid-team/torch-audiomentations#60]
Maybe we could use this? https://github.com/jonashaag/numpy-fast-align-mse

**Comment by mpariente** [comment]
This would be cool but it's on CPU, without batch.. 
Argmax of the abs on the RIR gives the delay, would that be ok?

**Comment by iver56** [comment]
Yes, in most cases that works well enough

**Comment by jonashaag** [comment]
FYI I use argmax for RIR delay and the MSE brute force method for other delays (eg. ffmpeg introduces random delays on left of a signal if you encode with some particular codecs)

**Comment by hbredin** [comment]
I just opened a PR that does just that (argmax of abs): #83
