### ISSUE TITLE
Bug: AddBackgroundNoise does not support CUDA.

### ISSUE THREAD

**Issue by janvainer** [asteroid-team/torch-audiomentations#70]
I am getting `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cpu!`.
I send my audio to cuda:2 and pass it to the augmentor and I get the error above. Same problem with Rirs. I also tried to send the augmentor itself to GPU, but this did not help. Is this a known issue?
`

**Comment by iver56** [comment]
Thanks for the report. I guess I will have to write a test for this

**Comment by iver56** [comment]
I was able to reproduce the bug in AddBackgroundNoise. Added a fix here: https://github.com/asteroid-team/torch-audiomentations/pull/71

However, I did not find a problem when passing cuda tensors to ApplyImpulseResponse. Is that what you meant with "Rirs"?

**Comment by hbredin** [comment]
Oooops, sorry I missed that as I only ever used this on CPU.

**Comment by iver56** [comment]
@janvainer You may open a separate issue for your problem with rirs

**Comment by janvainer** [comment]
Hey thanks for swift response! :) I double checked the RIRs and the problem was on my side. Sorry for the chaos. Are you going to do a new pip release with the fix soon? If no, is it possible to simply install master 
with `pip install <this repo installable url>`?

**Comment by iver56** [comment]
I'll make a release very soon. I want to merge this first: https://github.com/asteroid-team/torch-audiomentations/pull/73

**Comment by janvainer** [comment]
Ok no rush. This works `pip install git+https://github.com/asteroid-team/torch-audiomentations.git#egg=torch-audiomentations`

**Comment by iver56** [comment]
v0.5.1 is released on PyPI
