### ISSUE TITLE
Link to Pyroppl License in fft and convolve code 

### ISSUE THREAD

**Issue by mpariente** [asteroid-team/torch-audiomentations#78]
It would make more sense to have a header saying that it's copied or adapted from there. 
See the [original implementation](https://github.com/pyro-ppl/pyro/blob/dev/pyro/ops/tensor_utils.py#L170).

**Comment by iver56** [comment]
Pyro is already mentioned in each function that is copied from there, e.g.
https://github.com/asteroid-team/torch-audiomentations/blob/master/torch_audiomentations/utils/convolution.py#L46

What more is needed? Would you like to make a pull request?

**Comment by mpariente** [comment]
I expected a header in the file and I didn't spend enough time checking the docstring, very sorry about that.
