### ISSUE TITLE
Implement a transform that crops audio to a given length

### ISSUE THREAD

**Issue by iver56** [asteroid-team/torch-audiomentations#97]
The offset can be randomized, as long as the output has the specified length

Like https://github.com/Spijkervet/torchaudio-augmentations/blob/d044f9d020e12032ab9280acf5f34a337e72d212/torchaudio_augmentations/augmentations/random_resized_crop.py#L5

The idea is that one can have a chain of transforms, and some of them change the input length, but the final length should be fixed. That is where this transform is handy.

**Comment by swagshaw** [comment]
@iver56  Hello, is this issue still opening? I would like to take it.

**Comment by iver56** [comment]
Hi :) Yes, go ahead

**Comment by shahules786** [comment]
@iver56 Do you want to close this issue?
